package com.nexus.core.media.processor.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 处理选项配置类
 * 
 * 定义媒体处理的各种选项和参数。
 * 
 * @author MediaProcessor Module
 * @version 1.0.0
 * @since 2024-01-01
 */
@Parcelize
data class ProcessingOptions(
    /** 是否覆盖已存在的文件 */
    val overwriteExisting: Boolean = false,
    
    /** 是否下载字幕 */
    val downloadSubtitles: Boolean = false,
    
    /** 字幕语言列表 */
    val subtitleLanguages: List<String> = emptyList(),
    
    /** 是否下载缩略图 */
    val downloadThumbnail: Boolean = false,
    
    /** 是否嵌入字幕 */
    val embedSubtitles: Boolean = false,
    
    /** 是否嵌入缩略图 */
    val embedThumbnail: Boolean = false,
    
    /** 自定义文件名模板 */
    val filenameTemplate: String? = null,
    
    /** 输出格式转换 */
    val outputFormat: String? = null,
    
    /** 视频质量限制 */
    val maxVideoHeight: Int? = null,
    
    /** 音频质量限制 */
    val maxAudioBitrate: Int? = null,
    
    /** 是否仅提取音频 */
    val audioOnly: Boolean = false,
    
    /** 是否仅提取视频 */
    val videoOnly: Boolean = false,
    
    /** 偏好的媒体质量 */
    val preferredQuality: MediaQuality = MediaQuality.BEST,
    
    /** 开始时间(秒) */
    val startTime: Int? = null,
    
    /** 结束时间(秒) */
    val endTime: Int? = null,
    
    /** 自定义用户代理 */
    val customUserAgent: String? = null,
    
    /** 自定义请求头 */
    val customHeaders: Map<String, String> = emptyMap(),
    
    /** 代理设置 */
    val proxyUrl: String? = null,
    
    /** 是否使用aria2下载 */
    val useAria2: Boolean = false,
    
    /** aria2配置 */
    val aria2Options: Map<String, String> = emptyMap(),
    
    /** 后处理选项 */
    val postProcessingOptions: PostProcessingOptions = PostProcessingOptions(),
    
    /** 是否创建子目录 */
    val createSubdirectory: Boolean = false,
    
    /** 子目录模式 */
    val subdirectoryPattern: String = "date"
) : Parcelable

/**
 * 后处理选项
 */
@Parcelize
data class PostProcessingOptions(
    /** 是否启用后处理 */
    val enabled: Boolean = false,
    
    /** 是否重新编码视频 */
    val reencodeVideo: Boolean = false,
    
    /** 是否重新编码音频 */
    val reencodeAudio: Boolean = false,
    
    /** 目标视频编码 */
    val targetVideoCodec: String? = null,
    
    /** 目标音频编码 */
    val targetAudioCodec: String? = null,
    
    /** 视频比特率 */
    val videoBitrate: String? = null,
    
    /** 音频比特率 */
    val audioBitrate: String? = null,
    
    /** 是否添加元数据 */
    val addMetadata: Boolean = true,
    
    /** 自定义FFmpeg参数 */
    val customFFmpegArgs: List<String> = emptyList()
) : Parcelable

/**
 * 缩略图信息
 */
@Parcelize
data class ThumbnailInfo(
    /** 缩略图ID */
    val id: String,
    
    /** 缩略图URL */
    val url: String,
    
    /** 宽度 */
    val width: Int,
    
    /** 高度 */
    val height: Int,
    
    /** 分辨率描述 */
    val resolution: String? = null,
    
    /** 文件扩展名 */
    val extension: String? = null,
    
    /** 文件大小 */
    val fileSize: Long? = null,
    
    /** 偏好值 */
    val preference: Int? = null
) : Parcelable {
    
    /**
     * 获取分辨率字符串
     */
    fun getResolutionString(): String {
        return resolution ?: "${width}x${height}"
    }
    
    /**
     * 获取像素总数
     */
    fun getPixelCount(): Int {
        return width * height
    }
    
    /**
     * 检查是否为高清缩略图
     */
    fun isHighDefinition(): Boolean {
        return width >= 1280 || height >= 720
    }
}

/**
 * 字幕信息
 */
@Parcelize
data class SubtitleInfo(
    /** 字幕ID */
    val id: String,
    
    /** 语言代码 */
    val language: String,
    
    /** 语言名称 */
    val languageName: String,
    
    /** 字幕URL */
    val url: String,
    
    /** 字幕格式 */
    val format: String,
    
    /** 文件扩展名 */
    val extension: String,
    
    /** 是否为自动生成 */
    val isAutoGenerated: Boolean = false,
    
    /** 是否为默认字幕 */
    val isDefault: Boolean = false,
    
    /** 文件大小 */
    val fileSize: Long? = null
) : Parcelable {
    
    /**
     * 获取显示名称
     */
    fun getDisplayName(): String {
        val autoTag = if (isAutoGenerated) " (自动)" else ""
        val defaultTag = if (isDefault) " (默认)" else ""
        return "$languageName$autoTag$defaultTag"
    }
}

/**
 * 章节信息
 */
@Parcelize
data class ChapterInfo(
    /** 章节标题 */
    val title: String,
    
    /** 开始时间(秒) */
    val startTime: Float,
    
    /** 结束时间(秒) */
    val endTime: Float?
) : Parcelable {
    
    /**
     * 获取章节时长
     */
    fun getDuration(): Float? {
        return endTime?.let { it - startTime }
    }
    
    /**
     * 获取格式化的开始时间
     */
    fun getFormattedStartTime(): String {
        return formatTime(startTime)
    }
    
    /**
     * 获取格式化的结束时间
     */
    fun getFormattedEndTime(): String? {
        return endTime?.let { formatTime(it) }
    }
    
    /**
     * 获取格式化的时长
     */
    fun getFormattedDuration(): String? {
        return getDuration()?.let { formatTime(it) }
    }
    
    private fun formatTime(seconds: Float): String {
        val totalSeconds = seconds.toInt()
        val hours = totalSeconds / 3600
        val minutes = (totalSeconds % 3600) / 60
        val secs = totalSeconds % 60
        
        return if (hours > 0) {
            String.format("%d:%02d:%02d", hours, minutes, secs)
        } else {
            String.format("%d:%02d", minutes, secs)
        }
    }
}

/**
 * 媒体质量枚举
 */
enum class MediaQuality {
    BEST,       // 最佳质量
    WORST,      // 最低质量
    UHD_4K,     // 4K超高清
    QHD_2K,     // 2K高清
    FHD_1080P,  // 1080P全高清
    HD_720P,    // 720P高清
    SD_480P,    // 480P标清
    SD_360P,    // 360P标清
    SD_240P,    // 240P标清
    LOW,        // 低质量 (≤480p)
    MEDIUM,     // 中等质量 (481p-720p)
    HIGH,       // 高质量 (721p-1080p)
    ULTRA,      // 超高质量 (>1080p)
    AUDIO_ONLY  // 仅音频
}

/**
 * 网络类型枚举
 */
enum class NetworkType {
    WIFI,       // WiFi网络
    MOBILE,     // 移动网络
    ETHERNET,   // 以太网
    UNKNOWN     // 未知网络
}





/**
 * 处理事件
 */
sealed class ProcessingEvent {
    data class TaskCreated(val task: ProcessingTask) : ProcessingEvent()
    data class TaskStarted(val task: ProcessingTask) : ProcessingEvent()
    data class TaskProgress(val task: ProcessingTask, val progress: Int) : ProcessingEvent()
    data class TaskPaused(val task: ProcessingTask) : ProcessingEvent()
    data class TaskResumed(val task: ProcessingTask) : ProcessingEvent()
    data class TaskCompleted(val task: ProcessingTask) : ProcessingEvent()
    data class TaskFailed(val task: ProcessingTask, val error: String) : ProcessingEvent()
    data class TaskCancelled(val task: ProcessingTask) : ProcessingEvent()
    data class TaskDeleted(val taskId: String) : ProcessingEvent()
}