storeFile=debug.jks
storePassword=123456
keyAlias=key0
keyPassword=123456


packageName=com.app.videobox
admobId=ca-app-pub-3940256099942544~3347511713
facebookId=123456789
facebookToken=abcdefghijklnmopqrstuvwxyz
afKey=FUgiGjUjPRu5wv9qUYizt9

privacyUrl=https://docs.google.com/document/d/1_mk_vF1DTJS3mg0Q1k3silAplOdPAJFD8KQjKzNpQkM/edit?usp=sharing
termUrl=https://docs.google.com/document/d/1habE5xc5i9dHk1nDVmXcUE-FTwmvHWaMQ4QSFVWTIMU/edit?usp=sharing
