storeFile=my-release-key.jks
storePassword=Iofehfuh
keyAlias=my-key-alias
keyPassword=Iofehfuh


packageName=com.app.videobox
admobId=ca-app-pub-3940256099942544~3347511713
facebookId=123456789
facebookToken=abcdefghijklnmopqrstuvwxyz
afKey=

privacyUrl=https://docs.google.com/document/d/1_mk_vF1DTJS3mg0Q1k3silAplOdPAJFD8KQjKzNpQkM/edit?usp=sharing
termUrl=https://docs.google.com/document/d/1habE5xc5i9dHk1nDVmXcUE-FTwmvHWaMQ4QSFVWTIMU/edit?usp=sharing
