storeFile=my-release-key.jks
storePassword=Iofehfuh
keyAlias=my-key-alias
keyPassword=Iofehfuh


packageName=com.app.videobox
admobId=ca-app-pub-3940256099942544~3347511713
facebookId=123456789
facebookToken=abcdefghijklnmopqrstuvwxyz


privacyUrl=https://docs.google.com/document/d/1cxvinbzRx4R8ZiozShziGjH6bL9EQiezqhhPsNuTby8/edit?usp=sharing
